### ISSUE TITLE
Is the tutorial up-to-date?

### ISSUE THREAD

**Issue by bernardo-cruz** [IBM/virtual-insurance-assistant#24]
Is the showed tutorial (readme.md) up to date? I was trying to follow along with the files-to-be-downloaded etc. and it seems to be not working.

**Comment by rhagarty** [comment]
@bernardo-cruz A new V2 version of Watson Discovery was just released on IBM Cloud and is incompatible with this code pattern. There are plans to update this material, but no firm date on that.
